on: []
name: bot-update
env:
    USER: ${{secrets.USERNAME}}
    PASSWORD: ${{secrets.PASSWORD}}
on:
  schedule:
    - cron: 0 2 * * 0-5
jobs:
  bot-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm start
