on:
  schedule:
    - cron: 0 0 * * 0-5
  workflow_dispatch:
jobs:
  lockAspaklaryaPages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        if: ${{ always() }}
        continue-on-error: true
        with:
          name: last_successful_run_lock_pages
      - name: Read last run date
        run: |
          if [ -f last_successful_run_lock_pages.txt ]; then
            echo "LAST_RUN=$(cat last_successful_run_lock_pages.txt)" >> $GITHUB_ENV
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm install
      - name: lock and unlock pages
        run: node src/scriptes/manageLockPage.js
        env:
          MC_USER: ${{secrets.MC_USER}}
          MC_PASSWORD: ${{secrets.MC_PASSWORD}}
      - name: Update last run
        if: success()
        run: |
          echo $(date -u +'%Y-%m-%dT%H:%M:%S.000Z') > last_successful_run_lock_pages.txt
          echo "ARTIFACT_DAY=$(date -u +'%a')" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: last_successful_run_lock_pages
          path: last_successful_run_lock_pages.txt
      - uses: actions/upload-artifact@v4
        with:
          name: logs_${{env.ARTIFACT_DAY}}_$GITHUB_WORKFLOW
          path: ./logs
